apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-s3-app
  labels:
    app: flask-s3-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-s3-app
  template:
    metadata:
      labels:
        app: flask-s3-app
    spec:
      containers:
      - name: flask-s3-app
        image: flask-s3-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: S3_BUCKET_NAME
          value: "myflaskbucket2025"  # Thay bằng tên bucket thật
        - name: S3_REGION
          value: "ap-northeast-1"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-s3-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-s3-credentials
              key: AWS_SECRET_ACCESS_KEY
        - name: SECRET_KEY
          value: "your-flask-secret-key-change-in-production"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-s3-service
spec:
  type: NodePort
  selector:
    app: flask-s3-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080
